package dev.counterline.core.content

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import dev.counterline.core.model.ClaimsManifest
import dev.counterline.core.model.Deviation
import dev.counterline.core.model.Drill
import dev.counterline.core.model.ModelGame
import dev.counterline.core.model.Plan
import dev.counterline.core.model.ProofMatch
import dev.counterline.core.model.QuickStart
import dev.counterline.core.model.RepertoireLine
import dev.counterline.core.model.Theme
import kotlinx.serialization.json.Json
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Loads structured content JSON from bundled assets.
 * All JSON files live under assets/content/ and are generated by the
 * extract_content.py script from the repo manifests and book chapters.
 */
@Singleton
class ContentAssetLoader @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val json = Json { ignoreUnknownKeys = true; isLenient = true }

    private fun readAsset(name: String): String =
        context.assets.open("content/$name").bufferedReader().use { it.readText() }

    fun loadRepertoireLines(): List<RepertoireLine> =
        json.decodeFromString(readAsset("repertoire.json"))

    fun loadPlans(): List<Plan> =
        json.decodeFromString(readAsset("plans.json"))

    fun loadThemes(): List<Theme> =
        json.decodeFromString(readAsset("themes.json"))

    fun loadDeviations(): List<Deviation> =
        json.decodeFromString(readAsset("deviations.json"))

    fun loadModelGames(): List<ModelGame> =
        json.decodeFromString(readAsset("model_games.json"))

    fun loadDrills(): List<Drill> =
        json.decodeFromString(readAsset("drills.json"))

    fun loadClaimsManifest(): ClaimsManifest =
        json.decodeFromString(readAsset("claims.json"))

    fun loadProofMatches(): List<ProofMatch> =
        json.decodeFromString(readAsset("proof.json"))

    fun loadQuickStarts(): List<QuickStart> =
        json.decodeFromString(readAsset("quick_starts.json"))
}
